name: Publish to registry.npmjs.org

on: [push]

jobs:
  full:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Use Node.js 8.x
          uses: actions/setup-node@v1
          with:
            node-version: 8.x
        - name: npm install and test
          run: |
            npm install
            npm test      
        - name: publish
          env:
            NPM_DBASH: ${{ secrets.NPM_DBASH }}
          run: |
            npm install
            npm run compile
            npm config set '//registry.npmjs.org/:_authToken' "${NPM_DBASH}"
            npm publish
