name: Build, test and publish to NPM and GPR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run compile
      - run: npm run test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 12
      - run: npm ci
      - run: npm run compile
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DBASH }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@oocydo'
      - run: 'sed -i \'s/\"dbash\"/\"@oocydo\/dbash\"/\' package.json'
      - run: 'sed -i \'/  \"author\": \"oocydo\",/i \  \"publishConfig\": {\n    \"registry\": \"https:\/\/npm.pkg.github.com\/\"\n  },\' package.json'
      - run: npm ci
      - run: npm run compile
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_DBASH }}
